# Generated by Django 5.0.4 on 2024-05-06 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declarant', '0003_consignmentitem_xml_containerxml'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarantOrgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectBriefName', models.CharField(max_length=200)),
                ('TaxpayerId', models.CharField(max_length=12)),
                ('UnifiedCountryCode', models.CharField(max_length=3)),
                ('RegionName', models.CharField(blank=True, max_length=120, null=True)),
                ('CityName', models.CharField(max_length=120)),
                ('StreetName', models.CharField(max_length=120)),
                ('BuildingNumberId', models.CharField(blank=True, max_length=50, null=True)),
                ('RoomNumberId', models.CharField(blank=True, max_length=20, null=True)),
                ('RegistrationNumberId', models.CharField(max_length=50)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.CharField(help_text='!!! обязательно в формате +375 33 6262122', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NsMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_type', models.CharField(max_length=4)),
                ('name_field', models.CharField(max_length=15)),
                ('text_field', models.CharField(max_length=70)),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=8)),
                ('NAME', models.CharField(max_length=50)),
                ('COUNTRYCODEDIG', models.CharField(max_length=3)),
                ('COUNTRYCODELIT', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=10)),
                ('name_r', models.CharField(max_length=1000)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('sanction_type', models.CharField(blank=True, max_length=30, null=True)),
                ('sanction_descr', models.CharField(blank=True, max_length=700, null=True)),
                ('note', models.CharField(blank=True, max_length=320, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='transport',
            unique_together={('TransportMeansRegId', 'Carrier', 'TransportTypeCode')},
        ),
        migrations.AddField(
            model_name='carrierrepresentative',
            name='POA_DocCreationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrierrepresentative',
            name='POA_DocId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carrierrepresentative',
            name='POA_DocKindCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='carrierrepresentative',
            name='POA_DocValidityDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrierrepresentative',
            name='QualificationCertificateId',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='consignmentitem',
            name='CV_currencyCode',
            field=models.CharField(blank=True, default='BYN', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='consignmentitem',
            name='CargoPackageInfoKindCode',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='consignmentitem',
            name='CustomsValueAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='consignmentitem',
            name='GoodsTraceabilityCode',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='consignmentitem',
            name='LicenseGoodsKindCode',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='consignmentitem',
            name='TM_GoodsMeasure',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='consignmentitem',
            name='TM_MeasureUnitAbbreviationCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='consignmentitem',
            name='TM_measurementUnitCode',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='piprecedingdocdetails',
            name='ConsignmentItemOrdinal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tnved',
            name='Ta',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='transhipment',
            name='CustomsOfficeName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transport',
            name='DocId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transportxml',
            name='DocId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='CD_CommunicationChannelCode',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='CD_CommunicationChannelId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='CD_CommunicationChannelName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SD_RegisterDocumentIdDetails_DocKindCode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SD_RegisterDocumentIdDetails_RegistrationNumberId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SD_RepresentativeContractDetails_DocCreationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SD_RepresentativeContractDetails_DocId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SD_RepresentativeContractDetails_DocKindCode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SD_RepresentativeContractDetails_UnifiedCountryCode',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_DocCreationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_DocId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_DocValidityDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_FirstName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_IdentityDocKindCode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_LastName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_MiddleName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_POA_DocCreationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_POA_DocId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_POA_DocKindCode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_POA_DocValidityDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_PositionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_QualificationCertificateId',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='SP_UnifiedCountryCode',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='TD_CV_currencyCode',
            field=models.CharField(default='BYN', max_length=3),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='TD_CustomsValueAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='TD_ER_currencyCode',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='TD_ER_scaleNumber',
            field=models.CharField(default='0', max_length=6),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='TD_ExchangeRate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='TT_UnifiedCountryCode',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='XmlType',
            field=models.CharField(default='PIAT', max_length=4),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='transport_list',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='xmlmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carrierrepresentative',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='AGM_MeasureUnitAbbreviationCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='AGM_measurementUnitCode',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='CommodityCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='GM_MeasureUnitAbbreviationCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='GM_measurementUnitCode',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='GoodsDescriptionText',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='GoodsDescriptionText1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='GoodsDescriptionText2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='GoodsDescriptionText3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='PackageAvailabilityCode',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='consignmentitem',
            name='currencyCode',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='consignorconsignee',
            name='BuildingNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='consignorconsignee',
            name='RegionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='consignorconsignee',
            name='RoomNumberId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='consignorconsignee',
            name='TaxpayerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='declarantcarrier',
            name='BuildingNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='declarantcarrier',
            name='RegionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='declarantcarrier',
            name='RoomNumberId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='declarantcarrier',
            name='TaxpayerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pideclarant',
            name='BuildingNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pideclarant',
            name='RegionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='pideclarant',
            name='RoomNumberId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pideclarant',
            name='TaxpayerId',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transhipment',
            name='CargoOperationKindCode',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='transhipment',
            name='CustomsOfficeCode',
            field=models.CharField(blank=True, max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='transhipment',
            name='PlaceName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='transitguarantee',
            name='ES_BankId',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='transitguarantee',
            name='ES_SubjectBriefName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='transitguarantee',
            name='ES_TaxpayerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transitguarantee',
            name='GC_CustomsDocumentId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transitguarantee',
            name='GC_CustomsOfficeCode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='transitguarantee',
            name='RD_RegistrationNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transitguarantee',
            name='RD_UnifiedCountryCode',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='transitguarantee',
            name='currencyCode',
            field=models.CharField(blank=True, default='BYN', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='VehicleModelName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='transportxml',
            name='VehicleMakeName',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='transportxml',
            name='VehicleModelName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='CarrierRepresentative_IdentityDocKindCode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='CarrierRepresentative_MiddleName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Carrier_BuildingNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Carrier_RegionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Carrier_RoomNumberId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Carrier_TaxpayerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Consignee_BuildingNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Consignee_RegionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Consignee_RoomNumberId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Consignee_TaxpayerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Consignor_BuildingNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Consignor_RegionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Consignor_RoomNumberId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='Consignor_TaxpayerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='ECP_BorderCheckpointName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='ECP_CustomsOfficeCode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='LoadingListsPageQuantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='LoadingListsQuantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='PIDeclarant_BuildingNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='PIDeclarant_RegionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='PIDeclarant_RoomNumberId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='PIDeclarant_TaxpayerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='PreliminaryInformationUsageCode1',
            field=models.CharField(default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='PreliminaryInformationUsageCode2',
            field=models.CharField(default='06', max_length=2),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='PreliminaryInformationUsageCode3',
            field=models.CharField(default='14', max_length=2),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='SealId',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='SealQuantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TD_DocCreationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TD_DocId',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TD_DocKindCode',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TIRHolderId',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TIRId',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TIRPageOrdinal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TIRSeriesId',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TT_CustomsControlZoneId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TransitDeclarant_BuildingNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TransitDeclarant_RegionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TransitDeclarant_RoomNumberId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TransitDeclarant_TaxpayerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='TransitFeatureCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='UnionCarrier_BuildingNumberId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='UnionCarrier_RegionName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='UnionCarrier_RoomNumberId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='xmlmodel',
            name='UnionCarrier_TaxpayerId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DraftJSON',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=50, null=True)),
                ('dt_add', models.DateTimeField(auto_now_add=True)),
                ('json_data', models.TextField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRatesNBRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cur_ID', models.PositiveIntegerField()),
                ('Date', models.DateTimeField()),
                ('Cur_Abbreviation', models.CharField(max_length=3)),
                ('Cur_Scale', models.IntegerField()),
                ('Cur_Name', models.CharField(max_length=255)),
                ('Cur_OfficialRate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'unique_together': {('Cur_ID', 'Date')},
            },
        ),
        migrations.CreateModel(
            name='Excise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('DateFrom', models.DateField(null=True)),
                ('DateTo', models.DateField(null=True)),
                ('Rate', models.FloatField(blank=True, null=True)),
                ('Currency', models.CharField(blank=True, max_length=3)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('MeasureUnit', models.CharField(blank=True, max_length=20, null=True)),
                ('RateText', models.CharField(max_length=100)),
                ('TnvedID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declarant.tnved')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='declarant.declarantorginfo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
