# Generated by Django 5.0.4 on 2024-05-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0002_alter_structure_name_en_alter_t1_xml_acccodref6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='NAME_EN',
            field=models.TextField(),
        ),
    ]
