# Generated by Django 5.0.4 on 2024-05-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0003_alter_structure_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t1_xml',
            name='ComCodTarCodGDS10',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='ComOfInfDC25',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='ComOfInfDC25LNG',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='DocRefDC23',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='DocRefDCLNG',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='DocTypDC21',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='GooDesGDS23',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='GroMasGDS46',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='IteNumGDS7',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='PreDocRefAR26',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='PreDocRefLNG',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='PreDocTypAR21',
        ),
    ]
