# Generated by Django 5.0.4 on 2024-05-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0004_remove_t1_xml_comcodtarcodgds10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CouOfRouCodITI1', models.CharField(max_length=255, verbose_name='Код страны маршрута')),
            ],
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='CouOfRouCodITI1',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='KinOfPacGS23',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='MarNumOfPacGS21',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='MarNumOfPacGS21LNG',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='NumOfPacGS24',
        ),
    ]
