# Generated by Django 5.0.4 on 2024-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0006_routes_t1_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_document',
            name='ComOfInfDC25',
        ),
        migrations.RemoveField(
            model_name='pre_document',
            name='ComOfInfDC25LNG',
        ),
        migrations.AddField(
            model_name='t1_xml',
            name='CitTRACORSECGOO022',
            field=models.CharField(default=1, max_length=255, verbose_name='Город перевозчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t1_xml',
            name='CouCodTRACORSECGOO023',
            field=models.CharField(default=1, max_length=255, verbose_name='Код страны перевозчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t1_xml',
            name='NamTRACORSECGOO025',
            field=models.CharField(default=1, max_length=255, verbose_name='Название перевозчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t1_xml',
            name='PosCodTRACORSECGOO026',
            field=models.CharField(default=1, max_length=255, verbose_name='Почтовый индекс перевозчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t1_xml',
            name='StrNumTRACORSECGOO027',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес перевозчика'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t1_xml',
            name='TRACORSECGOO021LNG',
            field=models.CharField(default=2, max_length=255, verbose_name='Язык перевозчика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='CitCARTRA789',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='CitTRACORSEC038',
            field=models.CharField(max_length=255, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='CodPlUnHEA357',
            field=models.CharField(max_length=255, verbose_name='код места доставки'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='CouCodCARTRA587',
            field=models.CharField(max_length=255, verbose_name='Код страны'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='CouCodTRACORSEC039',
            field=models.CharField(max_length=255, verbose_name='Код страны'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='GuaRefNumGRNREF1',
            field=models.CharField(max_length=255, verbose_name='Номер гарантии'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='IntConRefMES11',
            field=models.CharField(max_length=255, verbose_name='Внутренний номер сообщения'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='NADCARTRA121',
            field=models.CharField(max_length=255, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='NamCARTRA121',
            field=models.CharField(max_length=255, verbose_name='Название транспортной компании'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='NamPC17',
            field=models.CharField(max_length=255, verbose_name='название перевозчика'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='NamTRACORSEC041',
            field=models.CharField(max_length=255, verbose_name='Название второго перевозчика'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='PosCodCARTRA121',
            field=models.CharField(max_length=255, verbose_name='Почтовый индекса'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='PosCodTRACORSEC042',
            field=models.CharField(max_length=255, verbose_name='Почтовый'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='StrAndNumCARTRA254',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='StrNumTRACORSEC043',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='TRACORSEC037LNG',
            field=models.CharField(max_length=255, verbose_name='Язык'),
        ),
    ]
