# Generated by Django 5.0.4 on 2024-09-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0007_remove_pre_document_comofinfdc25_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t1_xml',
            name='CitTRACORSECGOO022',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='CouCodTRACORSECGOO023',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='NamTRACORSECGOO025',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='PosCodTRACORSECGOO026',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='StrNumTRACORSECGOO027',
        ),
        migrations.RemoveField(
            model_name='t1_xml',
            name='TRACORSECGOO021LNG',
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='PosCodTRACORSEC042',
            field=models.CharField(max_length=255, verbose_name='Почтовый индекс'),
        ),
    ]
