# Generated by Django 5.0.4 on 2024-09-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t1', '0008_remove_t1_xml_cittracorsecgoo022_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EUEOPIID', models.CharField(max_length=255, verbose_name='проверка номера')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('index', models.CharField(max_length=255, verbose_name='Индекс')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('country', models.CharField(max_length=255, verbose_name='Код страны')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
            ],
        ),
        migrations.RenameModel(
            old_name='Recipient_sender',
            new_name='Recipient',
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='NamPC17',
            field=models.CharField(max_length=255, verbose_name='название поручителя'),
        ),
        migrations.AlterField(
            model_name='t1_xml',
            name='NamTRACORSEC041',
            field=models.CharField(max_length=255, verbose_name='Название отправителя'),
        ),
    ]
